languageCode = "en-us"
title = "DSE Halfday Workshop"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	description = "DSE Halfday Workshop"

	logo = "images/asset-hub.svg"
	favicon = "/images/asset-hub.png"

[params.palette]
    primary = "grey"
    accent  = "teal"

[params.font]
    text = "Roboto"
    code = "Roboto Mono"

[social]
	github  = "russkatz/dse-halfday-workshop"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


[[menu.main]]
	name   = "Half Day Workshops Introduction"
	url    = "/"
	weight = 10
[[menu.main]]
    name   = "Presales Interactions"
	weight = 20
[[menu.main]]
    name   = "Setup Instructions"
    weight = 30
[[menu.main]]
    name   = "Workshop Delivery"
    weight = 40
