#!/bin/bash
IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
IP=${IP#addr:}

echo "standing up docs"
#standup the docs
#install hugo
if [ ! -x /opt/hugo/hugo ]
then
  mkdir /opt
  sudo mkdir /opt/hugo
  wget -P /tmp/ https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz
  sudo tar -xvf /tmp/hugo_0.26_Linux-64bit.tar.gz -C /opt/hugo
fi

if [ $HOSTNAME == 'dc0vm0' ]
then
  echo 'HERE'
  #IP=$(cat /etc/hosts | grep node0_ext | awk '{print $1}')
  IP=$(curl --max-time 200 --retry 12 --retry-delay 5 -sS -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-04-02" | \
      jq .network.interface[0].ipv4.ipAddress[0].publicIpAddress | \
      tr -d '"')  echo 'ip   ' $IP
fi

git submodule update --init
git submodule sync

sudo pkill -f hugo

cd docs
/opt/hugo/hugo serve --bind 0.0.0.0  --appendPort  --baseUrl "http://${IP}/" --canonifyURLs true &
