#!/bin/sh

# This doesn't actually download studio, grab it from blob stor and extract it in /tmp
cd /tmp
sversion='6.0.2'
curl -sS -O https://dsetestdrivestor.blob.core.windows.net/studio/datastax-studio-$sversion.tar.gz
tar -xf datastax-studio-$sversion.tar.gz
mv datastax-studio-$sversion studio

echo "Downloading workbooks .."
wget --no-check-certificate --content-disposition -P /tmp https://github.com/russkatz/dse-halfday-workshop/raw/master/files/dse-workshop-studio.tar.gz

echo "Configuring DSE Studio .."
sed -i 's%baseDirectory: null%baseDirectory: /tmp/studio/dse-workshop-studio%g' /tmp/studio/conf/configuration.yaml
sed -i 's%httpBindAddress: localhost%httpBindAddress: 0.0.0.0%g' /tmp/studio/conf/configuration.yaml
sed -i 's%executionTimeoutMs: 0%executionTimeoutMs: 600000%g' /tmp/studio/conf/configuration.yaml
cd /tmp/studio
tar -zxf /tmp/dse-workshop-studio.tar.gz

echo "Starting DSE Studio .."
for pid in `ps -aef | grep [s]tudio-server | awk '{print $2}'`; do kill -9 $pid; done
sleep 5

rm -rf ~/.datastax_studio
nohup /tmp/studio/bin/server.sh &

echo "http://"`curl -s http://api.ipify.org`":9091"
